package entities;
// Generated Jun 8, 2016 12:51:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bukutelpon generated by hbm2java
 */
@Entity
@Table(name="bukutelpon"
    ,schema="public"
)
public class Bukutelpon  implements java.io.Serializable {


     private int id;
     private String nama;
     private String nohp;

    public Bukutelpon() {
    }

	
    public Bukutelpon(int id) {
        this.id = id;
    }
    public Bukutelpon(int id, String nama, String nohp) {
       this.id = id;
       this.nama = nama;
       this.nohp = nohp;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nama", length=50)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="nohp", length=20)
    public String getNohp() {
        return this.nohp;
    }
    
    public void setNohp(String nohp) {
        this.nohp = nohp;
    }




}


